# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: unfrozen-networking-test
services:
  - name: chat-api
    project: backend/Chat.API/Chat.API.csproj
    bindings:
      - port: 8081
    env:
      - ConnectionStrings:ChatApp="Host=localhost; Port=5551; Database=chat-db; Username=postgres; Password=123;"
    #      - ConnectionStrings:ChatApp="Host=localhost; Port=5551; Database=chat-db;"
    #      - PGPASSWORD=12345
    #      - PGUSER=chat-backend
    tags:
      - bc
  - name: chat-db
    image: postgres:12
    bindings:
      - connectionString: "Host=${host}; Port=${port}; Database=chat-db; Username=postgres; Password=123;"
        port: 5431
    env:
      - POSTGRES_PASSWORD=123
    tags:
      - db
